import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '00 · 开启学习之旅',
      items: [{type: 'autogenerated', dirName: '00-start'}],
      collapsed: false,
    },
    {
      type: 'category',
      label: '01 · 编程系统基石',
      items: [{type: 'autogenerated', dirName: '01-foundations'}],
    },
    {
      type: 'category',
      label: '02 · 系统设计之桥',
      items: [{type: 'autogenerated', dirName: '02-system-design-bridge'}],
    },
    {
      type: 'category',
      label: '03 · 数据、缓存与队列',
      items: [{type: 'autogenerated', dirName: '03-data-cache-queue'}],
    },
    {
      type: 'category',
      label: '04 · 设计模式与 LLD',
      items: [{type: 'autogenerated', dirName: '04-design-patterns-lld'}],
    },
    {
      type: 'category',
      label: '05 · 核心组件',
      items: [{type: 'autogenerated', dirName: '05-core-components'}],
    },
    {
      type: 'category',
      label: '06 · 云原生与企业级架构',
      items: [{type: 'autogenerated', dirName: '06-cloud-enterprise-industrial'}],
    },
    {
      type: 'category',
      label: '07 · LLM 系统',
      items: [{type: 'autogenerated', dirName: '07-llm-systems'}],
    },
    {
      type: 'category',
      label: '08 · RAG 检索增强',
      items: [{type: 'autogenerated', dirName: '08-rag'}],
    },
    {
      type: 'category',
      label: '09 · Agent 智能体架构',
      items: [{type: 'autogenerated', dirName: '09-agent-architectures'}],
    },
    {
      type: 'category',
      label: '10 · Multi-Agent 多智能体协议',
      items: [{type: 'autogenerated', dirName: '10-multi-agent-protocols'}],
    },
    {
      type: 'category',
      label: '11 · 生产级 AI 平台',
      items: [{type: 'autogenerated', dirName: '11-production-ai-platform'}],
    },
    {
      type: 'category',
      label: '12 · 毕业设计 Capstone',
      items: [{type: 'autogenerated', dirName: '12-capstone'}],
    },
    {
      type: 'category',
      label: '架构案例库 Atlas',
      items: [{type: 'autogenerated', dirName: 'atlas'}],
    },
    {
      type: 'category',
      label: '实战项目 Projects',
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
  ],
};

export default sidebars;
